name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.SSH_PRIVATE_KEY }}" ec2-user@35.171.22.218 "cd /home/ec2-user/apps/EduTrack && git pull origin main && ./deploy_app.sh"

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
